<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitulo 8 Prueba de t (Compración paramétrica entre dos grupos) | Guía de Métodos Estadísticos 2020</title>
  <meta name="description" content="Guía de Laboratorio para Métodos Estadísticos" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitulo 8 Prueba de t (Compración paramétrica entre dos grupos) | Guía de Métodos Estadísticos 2020" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Guía de Laboratorio para Métodos Estadísticos" />
  <meta name="github-repo" content="fjfernandezj/GUIA-ME-2020" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitulo 8 Prueba de t (Compración paramétrica entre dos grupos) | Guía de Métodos Estadísticos 2020" />
  
  <meta name="twitter:description" content="Guía de Laboratorio para Métodos Estadísticos" />
  

<meta name="author" content="Pablo Cortes" />
<meta name="author" content="Francisco Fernández" />


<meta name="date" content="2021-02-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prueba-de-chi-cuadrado-chi2.html"/>
<link rel="next" href="análisis-de-varianza-anova.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/box.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><center><img src="imagenes/umayor.png" alt="umayor" width="50%" height="50%"style="margin: 15px 0 0 0"></center></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenidos</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción a R y Rstudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#software-estadístico-r"><i class="fa fa-check"></i><b>1.1</b> Software estadístico R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#aspectos-básicos-de-r"><i class="fa fa-check"></i><b>1.1.1</b> Aspectos básicos de R</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#r-studio"><i class="fa fa-check"></i><b>1.2</b> R Studio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#conociendo-a-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Conociendo a Rstudio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html"><i class="fa fa-check"></i><b>2</b> Tipos de datos en R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#objetos-en-r"><i class="fa fa-check"></i><b>2.1</b> Objetos en R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#propiedades-de-los-objetos"><i class="fa fa-check"></i><b>2.1.1</b> Propiedades de los objetos</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#tipos-de-objetos"><i class="fa fa-check"></i><b>2.2</b> Tipos de Objetos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#objetos-de-valores-numéricos"><i class="fa fa-check"></i><b>2.2.1</b> Objetos de valores numéricos</a></li>
<li class="chapter" data-level="2.2.2" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#vectores"><i class="fa fa-check"></i><b>2.2.2</b> Vectores</a></li>
<li class="chapter" data-level="2.2.3" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#data-frames"><i class="fa fa-check"></i><b>2.2.3</b> Data frames</a></li>
<li class="chapter" data-level="2.2.4" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#valores-perdidos"><i class="fa fa-check"></i><b>2.2.4</b> Valores Perdidos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html"><i class="fa fa-check"></i><b>3</b> Lectura y manipulación de datos en RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#preparemos-los-datos-para-r"><i class="fa fa-check"></i><b>3.1</b> Preparemos los datos para R</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#qué-formato-de-archivos-reconoce-r"><i class="fa fa-check"></i><b>3.1.1</b> ¿Qué formato de archivos reconoce R?</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#importemos-los-datos-a-r"><i class="fa fa-check"></i><b>3.2</b> Importemos los datos a R</a></li>
<li class="chapter" data-level="3.3" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#exploremos-los-datos-a-r"><i class="fa fa-check"></i><b>3.3</b> Exploremos los datos a R</a></li>
<li class="chapter" data-level="3.4" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#exploremos-los-datos-r-con-la-libreria-dplyr"><i class="fa fa-check"></i><b>3.4</b> Exploremos los datos R con la libreria dplyr</a></li>
<li class="chapter" data-level="3.5" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#reducción-de-una-base-de-datos"><i class="fa fa-check"></i><b>3.5</b> Reducción de una base de datos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html"><i class="fa fa-check"></i><b>4</b> Visualización de datos en RStudio</a>
<ul>
<li class="chapter" data-level="4.1" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#gráfico-de-dispersión-o-scatterplot"><i class="fa fa-check"></i><b>4.1</b> Gráfico de dispersión o <em>Scatterplot</em></a></li>
<li class="chapter" data-level="4.2" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#diagrama-de-cajas-o-boxplot"><i class="fa fa-check"></i><b>4.2</b> Diagrama de cajas o <em>Boxplot</em></a></li>
<li class="chapter" data-level="4.3" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#histogramas"><i class="fa fa-check"></i><b>4.3</b> Histogramas</a></li>
<li class="chapter" data-level="4.4" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#ejercicios-para-la-casa"><i class="fa fa-check"></i><b>4.4</b> Ejercicios para la casa</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><i class="fa fa-check"></i><b>5</b> Estadística descriptiva: Medidas de tendencia central y dispersión</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>5.1</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#operadores-lógicos"><i class="fa fa-check"></i><b>5.1.1</b> Operadores lógicos</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>5.2</b> Medidas de dispersión</a></li>
<li class="chapter" data-level="5.3" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#tabla-resumen"><i class="fa fa-check"></i><b>5.3</b> Tabla Resumen</a></li>
<li class="chapter" data-level="5.4" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#gráfico-de-barras"><i class="fa fa-check"></i><b>5.4</b> Gráfico de Barras</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html"><i class="fa fa-check"></i><b>6</b> Estadística inferencial: Pruebas estadísticas</a>
<ul>
<li class="chapter" data-level="6.1" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-paramétricas."><i class="fa fa-check"></i><b>6.1</b> Pruebas paramétricas.</a></li>
<li class="chapter" data-level="6.2" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-no-paramétricas"><i class="fa fa-check"></i><b>6.2</b> Pruebas no-paramétricas</a></li>
<li class="chapter" data-level="6.3" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#normalidad"><i class="fa fa-check"></i><b>6.3</b> Normalidad</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#método-visual-histograma-de-frecuencia"><i class="fa fa-check"></i><b>6.3.1</b> Método visual: histograma de frecuencia</a></li>
<li class="chapter" data-level="6.3.2" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-estadísticas-prueba-de-shapiro-wilk"><i class="fa fa-check"></i><b>6.3.2</b> Pruebas estadísticas: prueba de Shapiro-Wilk</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#homocedasticidad"><i class="fa fa-check"></i><b>6.4</b> Homocedasticidad</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#método-visual-boxplot"><i class="fa fa-check"></i><b>6.4.1</b> Método visual: boxplot</a></li>
<li class="chapter" data-level="6.4.2" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-estadísticas-prueba-de-levene"><i class="fa fa-check"></i><b>6.4.2</b> Pruebas estadísticas: Prueba de Levene</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html"><i class="fa fa-check"></i><b>7</b> Prueba de chi-cuadrado (<span class="math inline">\(\chi^2\)</span>)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#prueba-de-bondad-de-ajuste"><i class="fa fa-check"></i><b>7.1</b> Prueba de bondad de ajuste</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#creemos-nuestros-datos"><i class="fa fa-check"></i><b>7.1.1</b> Creemos nuestros datos</a></li>
<li class="chapter" data-level="7.1.2" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#analicemos-nuestros-datos"><i class="fa fa-check"></i><b>7.1.2</b> Analicemos nuestros datos</a></li>
<li class="chapter" data-level="7.1.3" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#expresar-la-hipótesis-de-investigación"><i class="fa fa-check"></i><b>7.1.3</b> Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="7.1.4" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#calculemos-chi2-y-el-p-value"><i class="fa fa-check"></i><b>7.1.4</b> Calculemos <span class="math inline">\(\chi^2\)</span> y el p-value</a></li>
<li class="chapter" data-level="7.1.5" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#conclusión-del-test"><i class="fa fa-check"></i><b>7.1.5</b> Conclusión del test</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#prueba-de-independencia"><i class="fa fa-check"></i><b>7.2</b> Prueba de Independencia</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#cargar-nuestros-datos"><i class="fa fa-check"></i><b>7.2.1</b> Cargar nuestros datos</a></li>
<li class="chapter" data-level="7.2.2" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#analicemos-nuestros-datos-1"><i class="fa fa-check"></i><b>7.2.2</b> Analicemos nuestros datos</a></li>
<li class="chapter" data-level="7.2.3" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#expresar-la-hipótesis-de-investigación-1"><i class="fa fa-check"></i><b>7.2.3</b> Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="7.2.4" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#calculemos-chi2-y-el-p-value-1"><i class="fa fa-check"></i><b>7.2.4</b> Calculemos <span class="math inline">\(\chi^2\)</span> y el p-value</a></li>
<li class="chapter" data-level="7.2.5" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#conclusion-del-test"><i class="fa fa-check"></i><b>7.2.5</b> Conclusion del test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><i class="fa fa-check"></i><b>8</b> Prueba de t (Compración paramétrica entre dos grupos)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#ejemplo-1-prueba-de-t-para-muestras-independientes-de-diferentes-variedades-ejeplo-de-libro"><i class="fa fa-check"></i><b>8.1</b> Ejemplo 1: Prueba de t para muestras independientes de diferentes variedades (ejeplo de libro)</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#creemos-nuestros-datos-1"><i class="fa fa-check"></i><b>8.1.1</b> Creemos nuestros datos</a></li>
<li class="chapter" data-level="8.1.2" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#analicemos-nuestros-datos-2"><i class="fa fa-check"></i><b>8.1.2</b> Analicemos nuestros datos</a></li>
<li class="chapter" data-level="8.1.3" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#expresar-la-hipótesis-de-investigación-2"><i class="fa fa-check"></i><b>8.1.3</b> Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="8.1.4" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#realicemos-nuestra-prueba-de-t"><i class="fa fa-check"></i><b>8.1.4</b> Realicemos nuestra prueba de t</a></li>
<li class="chapter" data-level="8.1.5" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#conclusión-del-test-1"><i class="fa fa-check"></i><b>8.1.5</b> Conclusión del test</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#ejemplo-2-superficie-de-cultivos-por-zonas-cuando-las-condiciones-se-cumplen-y-no-se-cumplen"><i class="fa fa-check"></i><b>8.2</b> Ejemplo 2: Superficie de cultivos por zonas (Cuando las condiciones se cumplen y no se cumplen)</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#importemos-nuestros-datos"><i class="fa fa-check"></i><b>8.2.1</b> Importemos nuestros datos</a></li>
<li class="chapter" data-level="8.2.2" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#analicemos-nuestros-datos-cuando-las-condiciones-se-cumplen"><i class="fa fa-check"></i><b>8.2.2</b> Analicemos nuestros datos (Cuando las condiciones se cumplen)</a></li>
<li class="chapter" data-level="8.2.3" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#expresar-la-hipótesis-de-investigación-3"><i class="fa fa-check"></i><b>8.2.3</b> Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="8.2.4" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#realicemos-nuestra-prueba-de-t-1"><i class="fa fa-check"></i><b>8.2.4</b> Realicemos nuestra prueba de t</a></li>
<li class="chapter" data-level="8.2.5" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#conclusión-del-test-2"><i class="fa fa-check"></i><b>8.2.5</b> Conclusión del test</a></li>
<li class="chapter" data-level="8.2.6" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#analicemos-nuestros-datos-cuando-las-condiciones-no-se-cumplen"><i class="fa fa-check"></i><b>8.2.6</b> Analicemos nuestros datos (Cuando las condiciones NO se cumplen)</a></li>
<li class="chapter" data-level="8.2.7" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#prueba-de-mann-whitney-comparación-no-paramétrica-entre-dos-grupos"><i class="fa fa-check"></i><b>8.2.7</b> Prueba de Mann-Whitney (comparación no-paramétrica entre dos grupos)</a></li>
<li class="chapter" data-level="8.2.8" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#expresar-la-hipótesis-de-investigación-4"><i class="fa fa-check"></i><b>8.2.8</b> Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="8.2.9" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#realicemos-nuestra-prueba-de-mann-whitney"><i class="fa fa-check"></i><b>8.2.9</b> Realicemos nuestra prueba de Mann-Whitney</a></li>
<li class="chapter" data-level="8.2.10" data-path="prueba-de-t-compración-paramétrica-entre-dos-grupos.html"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#conclusión-del-test-3"><i class="fa fa-check"></i><b>8.2.10</b> Conclusión del test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html"><i class="fa fa-check"></i><b>9</b> Análisis de varianza (ANOVA)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#anova-de-1-vía"><i class="fa fa-check"></i><b>9.1</b> ANOVA de 1 Vía</a></li>
<li class="chapter" data-level="9.2" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#ejemplo"><i class="fa fa-check"></i><b>9.2</b> Ejemplo</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#los-datos"><i class="fa fa-check"></i><b>9.2.1</b> Los datos</a></li>
<li class="chapter" data-level="9.2.2" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#paso-1-analicemos-nuestros-datos"><i class="fa fa-check"></i><b>9.2.2</b> Paso 1: Analicemos nuestros datos</a></li>
<li class="chapter" data-level="9.2.3" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#paso-2-expresar-la-hipótesis-de-investigación"><i class="fa fa-check"></i><b>9.2.3</b> Paso 2: Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="9.2.4" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#paso-3-análisis-de-varianza-anova-de-una-vía"><i class="fa fa-check"></i><b>9.2.4</b> Paso 3: Análisis de Varianza (ANOVA de una vía)</a></li>
<li class="chapter" data-level="9.2.5" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#paso-4-evaluar-los-supuestos-del-modelo."><i class="fa fa-check"></i><b>9.2.5</b> Paso 4: Evaluar los supuestos del modelo.</a></li>
<li class="chapter" data-level="9.2.6" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#paso-5-interpretar-los-resultados-del-modelo"><i class="fa fa-check"></i><b>9.2.6</b> Paso 5: Interpretar los resultados del modelo</a></li>
<li class="chapter" data-level="9.2.7" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#paso-6-conclusión-del-test"><i class="fa fa-check"></i><b>9.2.7</b> Paso 6: Conclusión del test</a></li>
<li class="chapter" data-level="9.2.8" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#test-de-tukey-hsd-honestly-significance-difference"><i class="fa fa-check"></i><b>9.2.8</b> Test de Tukey HSD (Honestly Significance Difference)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html"><i class="fa fa-check"></i><b>10</b> Regresión lineal y correlación</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#modelos-lineales-generales"><i class="fa fa-check"></i><b>10.1</b> Modelos lineales generales</a></li>
<li class="chapter" data-level="10.2" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#correlación-producto-momento-de-pearson"><i class="fa fa-check"></i><b>10.2</b> Correlación producto-momento de Pearson</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#carguemos-nuestros-datos"><i class="fa fa-check"></i><b>10.2.1</b> Carguemos nuestros datos</a></li>
<li class="chapter" data-level="10.2.2" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-1-analicemos-nuestros-datos-1"><i class="fa fa-check"></i><b>10.2.2</b> Paso 1: Analicemos nuestros datos</a></li>
<li class="chapter" data-level="10.2.3" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-2-definir-la-hipótesis-que-queremos-poner-a-prueba."><i class="fa fa-check"></i><b>10.2.3</b> Paso 2: Definir la hipótesis que queremos poner a prueba.</a></li>
<li class="chapter" data-level="10.2.4" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-3-transformar-la-hipótesis-en-un-modelo-prueba-estadístico."><i class="fa fa-check"></i><b>10.2.4</b> Paso 3: Transformar la hipótesis en un modelo (prueba) estadístico.</a></li>
<li class="chapter" data-level="10.2.5" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-4-evaluar-los-supuestos-del-modelo.-1"><i class="fa fa-check"></i><b>10.2.5</b> Paso 4: Evaluar los supuestos del modelo.</a></li>
<li class="chapter" data-level="10.2.6" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-5-interpretar-los-resultados-del-modelo."><i class="fa fa-check"></i><b>10.2.6</b> Paso 5: Interpretar los resultados del modelo.</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#regresión-lineal-simple"><i class="fa fa-check"></i><b>10.3</b> Regresión Lineal Simple</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-1-graficar-nuestros-datos."><i class="fa fa-check"></i><b>10.3.1</b> Paso 1: Graficar nuestros datos.</a></li>
<li class="chapter" data-level="10.3.2" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-2-definir-la-hipótesis-que-queremos-poner-a-prueba.-1"><i class="fa fa-check"></i><b>10.3.2</b> Paso 2: Definir la hipótesis que queremos poner a prueba.</a></li>
<li class="chapter" data-level="10.3.3" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-3-transformar-la-hipótesis-en-un-modelo-prueba-estadístico.-1"><i class="fa fa-check"></i><b>10.3.3</b> Paso 3: Transformar la hipótesis en un modelo (prueba) estadístico.</a></li>
<li class="chapter" data-level="10.3.4" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-4-evaluar-los-supuestos-del-modelo.-2"><i class="fa fa-check"></i><b>10.3.4</b> Paso 4: Evaluar los supuestos del modelo.</a></li>
<li class="chapter" data-level="10.3.5" data-path="regresión-lineal-y-correlación.html"><a href="regresión-lineal-y-correlación.html#paso-5-interpretar-los-resultados-del-modelo.-1"><i class="fa fa-check"></i><b>10.3.5</b> Paso 5: Interpretar los resultados del modelo.</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Guía de Métodos Estadísticos 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="prueba-de-t-compración-paramétrica-entre-dos-grupos" class="section level1" number="8">
<h1><span class="header-section-number">Capitulo 8</span> Prueba de t (Compración paramétrica entre dos grupos)</h1>
<p>Uno de los análisis estadísticos más comunes es la prueba de t, la cual se utiliza para comparar la media de dos muestras dadas. Una prueba t se utiliza cuando no se conocen los parámetros de la población (media y desviación estándar).</p>
<p>La prueba t te dice cuán significativas son las diferencias entre los grupos, es decir, permite saber si esas diferencias (medidas en medias / promedios) podrían haber ocurrido por casualidad.</p>
<p>Hay tres versiones de prueba t</p>
<ol style="list-style-type: decimal">
<li><p>Prueba t de muestras independientes que compara la media de dos grupos</p></li>
<li><p>Prueba t de muestra pareada que compara medias del mismo grupo en diferentes momentos
Ejemplo:</p></li>
<li><p>Una prueba t de muestra que prueba la media de un solo grupo contra una media conocida.</p></li>
</ol>
<p>El estadístico para esta prueba de hipótesis se denomina estadístico t y se calcula como:</p>
<p><span class="math display">\[
t=\frac{(x_1 - x_2)}{\frac{σ}{\sqrt{n_1}} + \frac{σ}{\sqrt{n_2}}} \\
\]</span></p>
<p>donde:
<span class="math inline">\(x_1\)</span>: es la media de muestra 1</p>
<p><span class="math inline">\(x_2\)</span>: es la media de la muestra 2</p>
<p><span class="math inline">\(\sigma /\sqrt{n_1} + \sigma /\sqrt{n_2}\)</span>: es el error estandar de la diferencia de medias</p>
<p>Recuerden que este método nos permite examinar la relación entre una <strong>variable numérica</strong> y una <strong>variable explicativa categórica</strong></p>
<p>En el siguiente laboratorio veremos 2 ejemplos para muestras independientes</p>
<div id="ejemplo-1-prueba-de-t-para-muestras-independientes-de-diferentes-variedades-ejeplo-de-libro" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> Ejemplo 1: Prueba de t para muestras independientes de diferentes variedades (ejeplo de libro)</h2>
<div id="creemos-nuestros-datos-1" class="section level3" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Creemos nuestros datos</h3>
<p>ara ilustrar el uso de la prueba t, considere la muestra de seis rendimientos de una nueva variedad de trigo. Los rendimientos obtenidos fueron: 2.5, 2.1, 2.4, 2.0, 2.6 y 2.2 toneladas por hectárea. Suponga que, además de sus seis estimaciones de rendimiento con la nueva variedad, el agricultor tiene diez áreas similares con su variedad estándar con los siguientes rendimientos: 2.2, 1.9, 1.8, 2.1, 2.1, 1.7 también en toneladas por hectárea.</p>
<p>Para este ejemplo asumiremos que se cumplen las condiciones para efectuar un análisis parámetrico (Normalidad, Hemoscedasticidad, Independencia)</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creemos el vector rendimiento</span></span>
<span id="cb201-2"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb201-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos extraidos de Mead et al. (1993). Statistical Methods in Agriculture and Experimental Biology</span></span>
<span id="cb201-3"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb201-3" aria-hidden="true" tabindex="-1"></a>rendimiento <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.5</span>, <span class="fl">2.1</span>, <span class="fl">2.4</span>, <span class="fl">2.0</span>, <span class="fl">2.6</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>, <span class="fl">1.9</span>, <span class="fl">1.8</span>, <span class="fl">2.1</span>, <span class="fl">2.1</span>, <span class="fl">1.7</span> )</span>
<span id="cb201-4"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb201-4" aria-hidden="true" tabindex="-1"></a>variedad <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;var1&quot;</span>, <span class="dv">6</span>), <span class="fu">rep</span>(<span class="st">&quot;var2&quot;</span>, <span class="dv">6</span>))</span>
<span id="cb201-5"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb201-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb201-6"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb201-6" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(rendimiento, variedad)</span></code></pre></div>
</div>
<div id="analicemos-nuestros-datos-2" class="section level3" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Analicemos nuestros datos</h3>
<p>Veamos un resumen de nuestros datos</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb202-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## Warning: package &#39;tidyverse&#39; was built under R version 4.0.3</code></pre>
<pre><code>## -- Attaching packages ----------------------------------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.3     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.0</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 4.0.3</code></pre>
<pre><code>## Warning: package &#39;readr&#39; was built under R version 4.0.3</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.0.3</code></pre>
<pre><code>## -- Conflicts -------------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos)</span></code></pre></div>
<pre><code>##   rendimiento      variedad        
##  Min.   :1.700   Length:12         
##  1st Qu.:1.975   Class :character  
##  Median :2.100   Mode  :character  
##  Mean   :2.133                     
##  3rd Qu.:2.250                     
##  Max.   :2.600</code></pre>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb212-1" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb212-2"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb212-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(variedad) <span class="sc">%&gt;%</span> </span>
<span id="cb212-3"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb212-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">rendimiento_promedio =</span> <span class="fu">mean</span>(rendimiento))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb214-1" aria-hidden="true" tabindex="-1"></a>tabla</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   variedad rendimiento_promedio
##   &lt;chr&gt;                   &lt;dbl&gt;
## 1 var1                     2.3 
## 2 var2                     1.97</code></pre>
</div>
<div id="expresar-la-hipótesis-de-investigación-2" class="section level3" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Expresar la hipótesis de investigación</h3>
<p>Ahora realicemos una prueba de hipótesis. Queremos saber si los rendimientos son significativamente diferentes entre sí. ¿Cómo escribiríamos nuestras hipótesis?</p>
<p><span class="math display">\[
H_0: \text{Las medias de dos grupos son iguales} \\
H_a: \text{Las medias de dos grupos NO son iguales} \\
o \\
H_0: \mu_1 = \mu_2 \\
H_a: \mu_1 \neq \mu_2 \\
\]</span></p>
</div>
<div id="realicemos-nuestra-prueba-de-t" class="section level3" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Realicemos nuestra prueba de t</h3>
<p>Ahora analicemos nuestros datos a través de la prueba de t</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb216-1" aria-hidden="true" tabindex="-1"></a>res_ttest <span class="ot">&lt;-</span> <span class="fu">t.test</span>(rendimiento<span class="sc">~</span>variedad, <span class="at">data =</span> datos, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">conf=</span><span class="fl">0.95</span>)</span>
<span id="cb216-2"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb216-2" aria-hidden="true" tabindex="-1"></a>res_ttest</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rendimiento by variedad
## t = 2.6537, df = 9.6756, p-value = 0.0248
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.05218059 0.61448608
## sample estimates:
## mean in group var1 mean in group var2 
##           2.300000           1.966667</code></pre>
<p>Nuestra prueba estadística fue de 2.6537 con un p-value de 0.0248</p>
</div>
<div id="conclusión-del-test-1" class="section level3" number="8.1.5">
<h3><span class="header-section-number">8.1.5</span> Conclusión del test</h3>
<p>Ya que nuestro valor de probabilidad (<code>p-value</code>) es menor a 0.05 se rechaza la hipotesis nula. Por lo tanto, encontramos que los datos de nuestro modelo proporcionan evidencia estadísticamente significativa para sugerir que la media de los rendimientos de ambas variedades no son iguales.</p>
</div>
</div>
<div id="ejemplo-2-superficie-de-cultivos-por-zonas-cuando-las-condiciones-se-cumplen-y-no-se-cumplen" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Ejemplo 2: Superficie de cultivos por zonas (Cuando las condiciones se cumplen y no se cumplen)</h2>
<div id="importemos-nuestros-datos" class="section level3" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> Importemos nuestros datos</h3>
<p>En este práctico comenzaremos a trabajar
con una nueva base de datos que incluye las siguientes variables:</p>
<ul>
<li><p>Zona: Se refiere a zonas geográficas de nuestro país.</p></li>
<li><p>Region: Se refiere a divisiones territoriales oficiales de nuestro país.</p></li>
<li><p>Temporada: Año en que se realizan las mediciones.</p></li>
<li><p>Olivo: Superficie de territorio plantada con Olivos. Medida en hectáreas.</p></li>
<li><p>Chirimoyo: Superficie de territorio plantada con Chirimoyos. Medida en hectáreas</p></li>
<li><p>Vid: Superficie de territorio plantada con Vid de mesa. Medida en hectáreas.</p></li>
<li><p>Temperatura: Temperatura promedio anual en los puntos de muestreos. Medida en ºC.</p></li>
</ul>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb218-1" aria-hidden="true" tabindex="-1"></a>datos_p9 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;./datos/datosnuevos.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="analicemos-nuestros-datos-cuando-las-condiciones-se-cumplen" class="section level3" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> Analicemos nuestros datos (Cuando las condiciones se cumplen)</h3>
<div id="normalidad-1" class="section level4" number="8.2.2.1">
<h4><span class="header-section-number">8.2.2.1</span> Normalidad</h4>
<p>######Método visual: Histograma de frecuencia</p>
<p>Graficar un histograma de la variable de interés nos dará una idea de la forma de la distribución que siguen nuestros datos. Recordemos que la distribución normal alcanza su punto máximo en el medio y es simétrica respecto a la media. No es necesario que los datos se distribuyan de manera perfectamente normal para que las pruebas sean confiables.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(datos_p9<span class="sc">$</span>Olivo)</span></code></pre></div>
<p><img src="08-lab_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Nuestro análisis visual sugiere que los datos del número de hectáreas plantadas con olivos siguen una distribución normal. Sin embargo, esto no se cumple para el número de hectáreas plantadas con chirimoyos.</p>
<p>A pesar de ser informativo, el análisis visual es subjetivo porque dependemos de la interpretación de los gráficos. Una alternativa objetiva es el uso de análisis estadísticos basados en contrastes de hipótesis</p>
<div id="pruebas-estadísticas-test-de-shapiro-wilk" class="section level5" number="8.2.2.1.1">
<h5><span class="header-section-number">8.2.2.1.1</span> Pruebas estadísticas: Test de Shapiro-Wilk</h5>
<p>En estadística, el test de Shapiro–Wilk se usa para contrastar la normalidad de un conjunto de datos. Se pondrán a prueba las siguientes hipótesis:</p>
<p><span class="math display">\[
H_0 = \text{Los datos provienen de una distribución normal}\\
H_A = \text{Los datos NO provienen de una distribución normal}
\]</span></p>
<p>Recuerden si el valor de probabilidad es mayor a 0.05, no rechazamos la hipótesis nula y asumimos que los datos provienen de una distribución normal.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb220-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(datos_p9<span class="sc">$</span>Olivo)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  datos_p9$Olivo
## W = 0.98212, p-value = 0.112</code></pre>
<p>El valor de probabilidad (p&gt;0.05) asociado a nuestro análisis sugiere que los datos del número de hectáreas plantadas con olivos siguen una distribución normal.</p>
</div>
</div>
<div id="homocedasticidad-1" class="section level4" number="8.2.2.2">
<h4><span class="header-section-number">8.2.2.2</span> Homocedasticidad</h4>
<p>Visualizar un gráfico de cajas de la variable de interés nos dará una idea de la dispersión de los datos en torno a una medida de tendencia central. Para ello podemos considerar el tamaño de los bigotes de nuestro gráfico de cajas.</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(datos_p9<span class="sc">$</span>Olivo <span class="sc">~</span> datos_p9<span class="sc">$</span>Zona)</span></code></pre></div>
<p><img src="08-lab_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Nuestro análisis visual muestra que los datos del número de hectáreas plantadas con olivos presentan niveles similares de dispersión entorno a la mediana.</p>
<p>Otra opción es comparar directamente los valores de las varianza entre los grupos de interés. Para ello utilizaremos la función tapply:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb223-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(datos_p9<span class="sc">$</span>Olivo, datos_p9<span class="sc">$</span>Zona, var)</span></code></pre></div>
<pre><code>##   centro    norte 
## 6797.021 7222.925</code></pre>
<p>Los valores muestran que la varianza del número de hectáreas plantadas con olivos es 6% mayor en plantaciones de la zona norte en comparación a la zona sur.</p>
<p>A pesar de ser informativo, el análisis visual es subjetivo porque dependemos de la interpretación de los gráficos. Una alternativa objetiva es el uso de pruebas estadísticas basadas en contraste de hipótesis.</p>
<div id="pruebas-estadísticas-test-levene" class="section level5" number="8.2.2.2.1">
<h5><span class="header-section-number">8.2.2.2.1</span> Pruebas estadísticas: Test Levene</h5>
<p>En estadística, el test de Shapiro–Wilk se usa para evaluar la igualdad de las varianzas (homocedasticidad) para una variable calculada para dos o más grupos. Se pondrán a prueba las siguientes hipótesis:</p>
<p><span class="math display">\[
H_0 = \text{Las varianzas poblacionales de los grupos son iguales} \\
H_A = \text{Las varianzas poblacionales de los grupos NO son iguales}
\]</span></p>
<p>Recuerden que el p-value asociado al análisis nos permitirá rechazar (p &lt; 0.05) o no (p &gt; 0.05) nuestra hipótesis nula.</p>
<p>Recuerden que la función leveneTest es parte de la librería car. Es por ello que necesitamos instalar y cargar esta librería antes de hacer el análisis.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb225-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(datos_p9<span class="sc">$</span>Olivo <span class="sc">~</span> datos_p9<span class="sc">$</span>Zona)</span></code></pre></div>
<pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  0.0169 0.8969
##       118</code></pre>
<p>El valor de probabilidad (p&gt;0.05) asociado a nuestro análisis sugiere que las varianzas poblacionales del número de hectáreas plantadas con olivos son estadísticamente iguales para las muestras de la zona norte y central.</p>
<p>Dado que nuestra variable número de hectáreas plantadas con olivos cumple con los supuestos de normalidad y homocedasticidad, podemos aplicar métodos estadísticos paramétricos sobre ella.</p>
</div>
</div>
</div>
<div id="expresar-la-hipótesis-de-investigación-3" class="section level3" number="8.2.3">
<h3><span class="header-section-number">8.2.3</span> Expresar la hipótesis de investigación</h3>
<p>Pongamos ahora a prueba si existen diferencias en el número de hectáreas plantadas con olivos entre la zona norte y la zona central. Podemos hacerlo con una prueba de t si y solo si se cumplen los supuestos de normalidad de homogeneidad de varianza.</p>
<p><span class="math display">\[
H_0: \text{Las medias en el número de hectáreas en ambas zonas son iguales} \\
H_a: \text{Las medias en el número de hectáreas en ambas zonas NO son iguales.} \\
\]</span></p>
</div>
<div id="realicemos-nuestra-prueba-de-t-1" class="section level3" number="8.2.4">
<h3><span class="header-section-number">8.2.4</span> Realicemos nuestra prueba de t</h3>
<p>Ahora analicemos nuestros datos a través de la prueba de t</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb233-1" aria-hidden="true" tabindex="-1"></a>res_ttest_2 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Olivo<span class="sc">~</span>Zona, <span class="at">data =</span> datos_p9, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">conf=</span><span class="fl">0.95</span>)</span>
<span id="cb233-2"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb233-2" aria-hidden="true" tabindex="-1"></a>res_ttest_2</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Olivo by Zona
## t = -0.15777, df = 117.89, p-value = 0.8749
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -32.68265  27.85932
## sample estimates:
## mean in group centro  mean in group norte 
##             1497.470             1499.882</code></pre>
</div>
<div id="conclusión-del-test-2" class="section level3" number="8.2.5">
<h3><span class="header-section-number">8.2.5</span> Conclusión del test</h3>
<p>No hemos detectado diferencias estadísticamente significativas en el número de hectáreas plantadas con olivos entre la zona norte y la zona central. (t= -0.1577, P = 0.87), con un promedio de 1499±7222 hectáreas plantadas en la zona norte y un promedio de 1497±6797 hectáreas plantadas en la zona centro (promedio ± desvest).</p>
</div>
<div id="analicemos-nuestros-datos-cuando-las-condiciones-no-se-cumplen" class="section level3" number="8.2.6">
<h3><span class="header-section-number">8.2.6</span> Analicemos nuestros datos (Cuando las condiciones NO se cumplen)</h3>
<div id="normalidad-2" class="section level4" number="8.2.6.1">
<h4><span class="header-section-number">8.2.6.1</span> Normalidad</h4>
<p>######Método visual: Histograma de frecuencia</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(datos_p9<span class="sc">$</span>Chirimoyo)</span></code></pre></div>
<p><img src="08-lab_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>La distribución normal no se cumple para las hectáreas plantadas con chirimoyos</p>
</div>
</div>
<div id="prueba-de-mann-whitney-comparación-no-paramétrica-entre-dos-grupos" class="section level3" number="8.2.7">
<h3><span class="header-section-number">8.2.7</span> Prueba de Mann-Whitney (comparación no-paramétrica entre dos grupos)</h3>
<p>El test de Mann–Whitney, también conocido como Wilcoxon rank-sum test, es una prueba estadística no paramétrica que contrasta si dos muestras proceden de poblaciones equidistribuidas. Esta prueba estadística se fundamenta en que si las dos muestras comparadas proceden de la misma población, al juntar todas las observaciones y ordenarlas de menor a mayor, cabría esperar que las observaciones de una y otra muestra estuviesen intercaladas aleatoriamente. Por lo contrario, si una de las muestras pertenece a una población con valores mayores o menores que la otra población, al ordenar las observaciones estas tenderán a agruparse de modo que las de una muestra queden por encima de las de la otra.</p>
</div>
<div id="expresar-la-hipótesis-de-investigación-4" class="section level3" number="8.2.8">
<h3><span class="header-section-number">8.2.8</span> Expresar la hipótesis de investigación</h3>
<p>En este análisis se ponen a prueba las siguientes hipótesis:</p>
<p><span class="math display">\[
H_0: \text{La probabilidad de que una observación de la población X supere a una observación de la población Y es igual a la probabilidad de que una observación de la población Y supere a una de la población X}\\
H_A: \text{La probabilidad de que una observación de la población X supere a una observación de la población Y NO es igual a la probabilidad de que una observación de la población Y supere a una de la población X}
\]</span></p>
</div>
<div id="realicemos-nuestra-prueba-de-mann-whitney" class="section level3" number="8.2.9">
<h3><span class="header-section-number">8.2.9</span> Realicemos nuestra prueba de Mann-Whitney</h3>
<p>La función wilcox.test está disponible en R para realizar una prueba de Mann-Whitney.</p>
<p>Pongamos ahora a prueba si existen diferencias en el número de hectáreas plantadas con chirimoyos entre la zona norte y la zona central.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="prueba-de-t-compración-paramétrica-entre-dos-grupos.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(datos_p9<span class="sc">$</span>Chirimoyo<span class="sc">~</span>datos_p9<span class="sc">$</span>Zona)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  datos_p9$Chirimoyo by datos_p9$Zona
## W = 993.5, p-value = 2.33e-05
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div id="conclusión-del-test-3" class="section level3" number="8.2.10">
<h3><span class="header-section-number">8.2.10</span> Conclusión del test</h3>
<p>Los resultados se explican y reportan de la siguiente forma, existen diferencias estadísticamente significativas en el número de hectáreas plantadas con chirimoyos entre la zona norte y la zona central. (W=993.5, p&lt;0.05).</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="prueba-de-chi-cuadrado-chi2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análisis-de-varianza-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
