<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitulo 7 Prueba de chi-cuadrado (\(\chi^2\)) | Guía de Métodos Estadísticos 2020</title>
  <meta name="description" content="Guía de Laboratorio para Métodos Estadísticos" />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitulo 7 Prueba de chi-cuadrado (\(\chi^2\)) | Guía de Métodos Estadísticos 2020" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Guía de Laboratorio para Métodos Estadísticos" />
  <meta name="github-repo" content="fjfernandezj/GUIA-ME-2020" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitulo 7 Prueba de chi-cuadrado (\(\chi^2\)) | Guía de Métodos Estadísticos 2020" />
  
  <meta name="twitter:description" content="Guía de Laboratorio para Métodos Estadísticos" />
  

<meta name="author" content="Pablo Cortes" />
<meta name="author" content="Francisco Fernández" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estadística-inferencial-pruebas-estadísticas.html"/>
<link rel="next" href="estadística-inferencial-regresión-lineal-y-correlación.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css\style.css" type="text/css" />
<link rel="stylesheet" href="css\box.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><center><img src="imagenes/umayor.png" alt="umayor" width="50%" height="50%"style="margin: 15px 0 0 0"></center></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenidos</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción a R y Rstudio</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#software-estadístico-r"><i class="fa fa-check"></i><b>1.1</b> Software estadístico R</a><ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#aspectos-básicos-de-r"><i class="fa fa-check"></i><b>1.1.1</b> Aspectos básicos de R</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#r-studio"><i class="fa fa-check"></i><b>1.2</b> R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#conociendo-a-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Conociendo a Rstudio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html"><i class="fa fa-check"></i><b>2</b> Tipos de datos en R</a><ul>
<li class="chapter" data-level="2.1" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#objetos-en-r"><i class="fa fa-check"></i><b>2.1</b> Objetos en R</a><ul>
<li class="chapter" data-level="2.1.1" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#propiedades-de-los-objetos"><i class="fa fa-check"></i><b>2.1.1</b> Propiedades de los objetos</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#tipos-de-objetos"><i class="fa fa-check"></i><b>2.2</b> Tipos de Objetos</a><ul>
<li class="chapter" data-level="2.2.1" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#objetos-de-valores-numéricos"><i class="fa fa-check"></i><b>2.2.1</b> Objetos de valores numéricos</a></li>
<li class="chapter" data-level="2.2.2" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#vectores"><i class="fa fa-check"></i><b>2.2.2</b> Vectores</a></li>
<li class="chapter" data-level="2.2.3" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#data-frames"><i class="fa fa-check"></i><b>2.2.3</b> Data frames</a></li>
<li class="chapter" data-level="2.2.4" data-path="tipos-de-datos-en-r.html"><a href="tipos-de-datos-en-r.html#valores-perdidos"><i class="fa fa-check"></i><b>2.2.4</b> Valores Perdidos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html"><i class="fa fa-check"></i><b>3</b> Lectura y manipulación de datos en RStudio</a><ul>
<li class="chapter" data-level="3.1" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#preparemos-los-datos-para-r"><i class="fa fa-check"></i><b>3.1</b> Preparemos los datos para R</a><ul>
<li class="chapter" data-level="3.1.1" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#qué-formato-de-archivos-reconoce-r"><i class="fa fa-check"></i><b>3.1.1</b> ¿Qué formato de archivos reconoce R?</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#importemos-los-datos-a-r"><i class="fa fa-check"></i><b>3.2</b> Importemos los datos a R</a></li>
<li class="chapter" data-level="3.3" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#exploremos-los-datos-a-r"><i class="fa fa-check"></i><b>3.3</b> Exploremos los datos a R</a></li>
<li class="chapter" data-level="3.4" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#exploremos-los-datos-r-con-la-libreria-dplyr"><i class="fa fa-check"></i><b>3.4</b> Exploremos los datos R con la libreria dplyr</a></li>
<li class="chapter" data-level="3.5" data-path="lectura-y-manipulación-de-datos-en-rstudio.html"><a href="lectura-y-manipulación-de-datos-en-rstudio.html#reducción-de-una-base-de-datos"><i class="fa fa-check"></i><b>3.5</b> Reducción de una base de datos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html"><i class="fa fa-check"></i><b>4</b> Visualización de datos en RStudio</a><ul>
<li class="chapter" data-level="4.1" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#gráfico-de-dispersión-o-scatterplot"><i class="fa fa-check"></i><b>4.1</b> Gráfico de dispersión o <em>Scatterplot</em></a></li>
<li class="chapter" data-level="4.2" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#diagrama-de-cajas-o-boxplot"><i class="fa fa-check"></i><b>4.2</b> Diagrama de cajas o <em>Boxplot</em></a></li>
<li class="chapter" data-level="4.3" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#histogramas"><i class="fa fa-check"></i><b>4.3</b> Histogramas</a></li>
<li class="chapter" data-level="4.4" data-path="visualización-de-datos-en-rstudio.html"><a href="visualización-de-datos-en-rstudio.html#ejercicios-para-la-casa"><i class="fa fa-check"></i><b>4.4</b> Ejercicios para la casa</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><i class="fa fa-check"></i><b>5</b> Estadística descriptiva: Medidas de tendencia central y dispersión</a><ul>
<li class="chapter" data-level="5.1" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>5.1</b> Medidas de tendencia central</a><ul>
<li class="chapter" data-level="5.1.1" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#operadores-lógicos"><i class="fa fa-check"></i><b>5.1.1</b> Operadores lógicos</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>5.2</b> Medidas de dispersión</a></li>
<li class="chapter" data-level="5.3" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#tabla-resumen"><i class="fa fa-check"></i><b>5.3</b> Tabla Resumen</a></li>
<li class="chapter" data-level="5.4" data-path="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html"><a href="estadística-descriptiva-medidas-de-tendencia-central-y-dispersión.html#gráfico-de-barras"><i class="fa fa-check"></i><b>5.4</b> Gráfico de Barras</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html"><i class="fa fa-check"></i><b>6</b> Estadística inferencial: Pruebas estadísticas</a><ul>
<li class="chapter" data-level="6.1" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-paramétricas."><i class="fa fa-check"></i><b>6.1</b> Pruebas paramétricas.</a></li>
<li class="chapter" data-level="6.2" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-no-paramétricas"><i class="fa fa-check"></i><b>6.2</b> Pruebas no-paramétricas</a></li>
<li class="chapter" data-level="6.3" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#normalidad"><i class="fa fa-check"></i><b>6.3</b> Normalidad</a><ul>
<li class="chapter" data-level="6.3.1" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#método-visual-histograma-de-frecuencia"><i class="fa fa-check"></i><b>6.3.1</b> Método visual: histograma de frecuencia</a></li>
<li class="chapter" data-level="6.3.2" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-estadísticas-prueba-de-shapiro-wilk"><i class="fa fa-check"></i><b>6.3.2</b> Pruebas estadísticas: prueba de Shapiro-Wilk</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#homocedasticidad"><i class="fa fa-check"></i><b>6.4</b> Homocedasticidad</a><ul>
<li class="chapter" data-level="6.4.1" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#método-visual-boxplot"><i class="fa fa-check"></i><b>6.4.1</b> Método visual: boxplot</a></li>
<li class="chapter" data-level="6.4.2" data-path="estadística-inferencial-pruebas-estadísticas.html"><a href="estadística-inferencial-pruebas-estadísticas.html#pruebas-estadísticas-prueba-de-levene"><i class="fa fa-check"></i><b>6.4.2</b> Pruebas estadísticas: Prueba de Levene</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html"><i class="fa fa-check"></i><b>7</b> Prueba de chi-cuadrado (<span class="math inline">\(\chi^2\)</span>)</a><ul>
<li class="chapter" data-level="7.1" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#prueba-de-bondad-de-ajuste"><i class="fa fa-check"></i><b>7.1</b> Prueba de bondad de ajuste</a><ul>
<li class="chapter" data-level="7.1.1" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#creemos-nuestros-datos"><i class="fa fa-check"></i><b>7.1.1</b> Creemos nuestros datos</a></li>
<li class="chapter" data-level="7.1.2" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#analicemos-nuestros-datos"><i class="fa fa-check"></i><b>7.1.2</b> Analicemos nuestros datos</a></li>
<li class="chapter" data-level="7.1.3" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#expresar-la-hipótesis-de-investigación"><i class="fa fa-check"></i><b>7.1.3</b> Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="7.1.4" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#calculemos-chi2-y-el-p-value"><i class="fa fa-check"></i><b>7.1.4</b> Calculemos <span class="math inline">\(\chi^2\)</span> y el p-value</a></li>
<li class="chapter" data-level="7.1.5" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#conclusión-del-test"><i class="fa fa-check"></i><b>7.1.5</b> Conclusión del test</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#prueba-de-independencia"><i class="fa fa-check"></i><b>7.2</b> Prueba de Independencia</a><ul>
<li class="chapter" data-level="7.2.1" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#cargar-nuestros-datos"><i class="fa fa-check"></i><b>7.2.1</b> Cargar nuestros datos</a></li>
<li class="chapter" data-level="7.2.2" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#analicemos-nuestros-datos-1"><i class="fa fa-check"></i><b>7.2.2</b> Analicemos nuestros datos</a></li>
<li class="chapter" data-level="7.2.3" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#expresar-la-hipótesis-de-investigación-1"><i class="fa fa-check"></i><b>7.2.3</b> Expresar la hipótesis de investigación</a></li>
<li class="chapter" data-level="7.2.4" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#calculemos-chi2-y-el-p-value-1"><i class="fa fa-check"></i><b>7.2.4</b> Calculemos <span class="math inline">\(\chi^2\)</span> y el p-value</a></li>
<li class="chapter" data-level="7.2.5" data-path="prueba-de-chi-cuadrado-chi2.html"><a href="prueba-de-chi-cuadrado-chi2.html#conclusion-del-test"><i class="fa fa-check"></i><b>7.2.5</b> Conclusion del test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="estadística-inferencial-regresión-lineal-y-correlación.html"><a href="estadística-inferencial-regresión-lineal-y-correlación.html"><i class="fa fa-check"></i><b>8</b> Estadística inferencial: Regresión lineal y correlación</a><ul>
<li class="chapter" data-level="8.1" data-path="estadística-inferencial-regresión-lineal-y-correlación.html"><a href="estadística-inferencial-regresión-lineal-y-correlación.html#modelos-lineales-generales"><i class="fa fa-check"></i><b>8.1</b> Modelos Lineales generales</a><ul>
<li class="chapter" data-level="8.1.1" data-path="estadística-inferencial-regresión-lineal-y-correlación.html"><a href="estadística-inferencial-regresión-lineal-y-correlación.html#correlación-producto-momento-de-pearson"><i class="fa fa-check"></i><b>8.1.1</b> Correlación producto-momento de Pearson</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Guía de Métodos Estadísticos 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="prueba-de-chi-cuadrado-chi2" class="section level1">
<h1><span class="header-section-number">Capitulo 7</span> Prueba de chi-cuadrado (<span class="math inline">\(\chi^2\)</span>)</h1>
<p>La prueba de <span class="math inline">\(\chi^2\)</span> es una de las técnicas estadísticas más utilizadas en la evaluación de datos de conteo o frecuencias, principalmente en los análisis de tablas de contingencia (f x c) donde se resumen <strong>datos categóricos</strong>.</p>
<p>Existen dos tareas principales en las que podemos utilizar una prueba de Chi-cuadrado: Una prueba de bondad de ajuste (para una variable categórica) y una prueba de independencia (2 variables categóricas).</p>
<p>Es importante tener en cuenta que para utilizar una distribución <span class="math inline">\(\chi^2\)</span> como una aproximación teórica de distribucion, necesitamos chequear la condición de que cada uno de los conteos esperados sea al menos 5</p>
<div id="prueba-de-bondad-de-ajuste" class="section level2">
<h2><span class="header-section-number">7.1</span> Prueba de bondad de ajuste</h2>
<p>Esta variante de <span class="math inline">\(\chi^2\)</span> permite determinar qué tan bien una muestra de datos categóricos se ajusta a una distribución teórica (<span class="math inline">\(\chi^2\)</span>).</p>
<p>Para ilustrar el uso del test de (<span class="math inline">\(\chi^2\)</span>) consideremos el siguiente ejemplo:</p>
<div id="creemos-nuestros-datos" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Creemos nuestros datos</h3>
<p>Supongamos que deseamos probar el modelo de que los nacimientos masculinos y femeninos son igualmente probables para una raza particular de una especie y que una muestra aleatoria de nacimientos da como resultado 32 machos y 41 hembras.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1"><span class="co"># Datos extraidos de Mead et al. (1993). Statistical Methods in Agriculture and Experimental Biology</span></a>
<a class="sourceLine" id="cb160-2" title="2">sexo_nacimientos &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;Macho&quot;</span>, <span class="dv">32</span>), <span class="kw">rep</span>(<span class="st">&quot;Hembra&quot;</span>, <span class="dv">41</span>)) </a>
<a class="sourceLine" id="cb160-3" title="3">muestra &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">73</span>)</a>
<a class="sourceLine" id="cb160-4" title="4"></a>
<a class="sourceLine" id="cb160-5" title="5">data_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">data.frame</span>(muestra, sexo_nacimientos)</a></code></pre></div>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1"><span class="kw">head</span>(data_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>##   muestra sexo_nacimientos
## 1       1            Macho
## 2       2            Macho
## 3       3            Macho
## 4       4            Macho
## 5       5            Macho
## 6       6            Macho</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1"><span class="kw">tail</span>(data_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>##    muestra sexo_nacimientos
## 68      68           Hembra
## 69      69           Hembra
## 70      70           Hembra
## 71      71           Hembra
## 72      72           Hembra
## 73      73           Hembra</code></pre>
</div>
<div id="analicemos-nuestros-datos" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Analicemos nuestros datos</h3>
<p>Empecemos por ver un resumen de nuestros datos</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## -- Attaching packages ----------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 3.3.1     v purrr   0.3.4
## v tibble  2.1.3     v dplyr   0.8.3
## v tidyr   1.1.0     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.4.0</code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Warning: package &#39;purrr&#39; was built under R version 3.6.3</code></pre>
<pre><code>## -- Conflicts -------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" title="1">tabla &lt;-<span class="st"> </span>data_<span class="dv">1</span> <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb172-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(sexo_nacimientos) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb172-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n=</span><span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb172-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">proporcion =</span> n<span class="op">/</span><span class="kw">sum</span>(n))</a>
<a class="sourceLine" id="cb172-5" title="5"></a>
<a class="sourceLine" id="cb172-6" title="6">tabla</a></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   sexo_nacimientos     n proporcion
##   &lt;fct&gt;            &lt;int&gt;      &lt;dbl&gt;
## 1 Hembra              41      0.562
## 2 Macho               32      0.438</code></pre>
<p>También podemos graficar nuestros datos para tener una idea visual de nuestra muestra. Para esto podemos aplicar la función barplot() para generar un grafico con las frecuencias de las categorías de la variable. Ya que la función barplot() no muestra directamente las frecuencias de una variable categórica. Es necesario calcular previamente dichas frecuencias, para lo cual usaremos la función table()</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" title="1"><span class="kw">barplot</span>(<span class="kw">table</span>(data_<span class="dv">1</span><span class="op">$</span>sexo_nacimientos))</a></code></pre></div>
<p><img src="07-lab_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="expresar-la-hipótesis-de-investigación" class="section level3">
<h3><span class="header-section-number">7.1.3</span> Expresar la hipótesis de investigación</h3>
<p>Para este ejemplo vamos a considerar la variable <code>sexo_nacimientos</code> de nuestra base de datos que creamos anteriormente (<code>data</code>). De estos 73 nacimientos, esperaríamos que la mitad fueran machos y la otra mitad hembras. Por lo tanto, para esto nos gustaría estudiar la siguiente hipotesis:</p>
<p><span class="math display">\[
H_0: p_{\text{Hembra}} = 0.5, p_{\text{Macho}} = 0.5\\
H_a: \text{Las proporciones son diferentes}
\]</span></p>
</div>
<div id="calculemos-chi2-y-el-p-value" class="section level3">
<h3><span class="header-section-number">7.1.4</span> Calculemos <span class="math inline">\(\chi^2\)</span> y el p-value</h3>
<p>En R, la función <code>chisq.test</code> permite realizar pruebas de bondad de ajuste y de independencia de dos variables categóricas.</p>
<ul>
<li><code>chisq.test(x, y = NULL)</code></li>
</ul>
<p><strong>Donde:</strong></p>
<ul>
<li><p><code>x</code> Es un vector numérico o matriz. <code>x</code> e <code>y</code> también pueden ser ambos factores.</p></li>
<li><p><code>y</code> Es un vector numérico; ignorado si <code>x</code> es una matriz. Si <code>y</code> es un factor, <code>y</code> debe ser un factor de la misma longitud.</p></li>
</ul>
<p>Además, es posible extraer la siguiente información a partir del modelo generado:</p>
<ul>
<li><p><code>$statistic</code> El valor del estadístico de prueba de X<sup>2</sup>.</p></li>
<li><p><code>$p.value</code> El valor de probabilidad para la prueba.</p></li>
<li><p><code>$method</code> Una cadena de caracteres que indica el tipo de prueba realizada.</p></li>
<li><p><code>$data.name</code> Una cadena de caracteres que da el nombre(s) de los datos.</p></li>
<li><p><code>$observed</code> Los conteos observados.</p></li>
<li><p><code>$expected</code> Los conteos esperados bajo la hipótesis nula.</p></li>
<li><p><code>$residuals</code> Los residuos del modelo. Se calculan como (observado - esperado) / sqrt (esperado).</p></li>
</ul>
<p>Para probar si se cumple estadísticamente nuestras hipotesis usaremos la función <code>chisq.test</code>. Para este caso recuerden que debemos utilizar el conteo de cada categoría (Hembra y Macho).</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1">res_ajuste &lt;-<span class="st"> </span><span class="kw">chisq.test</span>(tabla<span class="op">$</span>n, <span class="dt">p =</span> <span class="kw">c</span>(<span class="fl">0.5</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb175-2" title="2">res_ajuste</a></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  tabla$n
## X-squared = 1.1096, df = 1, p-value = 0.2922</code></pre>
<p>Nuestra prueba estadística fue de 1.1096, con 1 grado de libertad y con un p-value de 0.29222</p>
</div>
<div id="conclusión-del-test" class="section level3">
<h3><span class="header-section-number">7.1.5</span> Conclusión del test</h3>
<p>Ya que nuestro valor de probabilidad (<code>p-value</code>) es mayor a 0.05 no se rechaza la hipotesis nula. Por lo tanto, encontramos que los datos de nuestro modelo no proporcionan evidencia estadísticamente significativa para rechazar la hipotesis nula de que los nacimientos masculinos y femeninos son igualmente probables.</p>
</div>
</div>
<div id="prueba-de-independencia" class="section level2">
<h2><span class="header-section-number">7.2</span> Prueba de Independencia</h2>
<p>Esta variante de <span class="math inline">\(\chi^2\)</span> permite determinar si el valor observado de una variable depende del valor observado de otra variable. Dicho de otro modo, se evalúa la relación entre dos variables categóricas.</p>
<p>Para esto consideremos los datos de siempre.</p>
<div id="cargar-nuestros-datos" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Cargar nuestros datos</h3>
<p>Recuerden que necesitaremos cargar nuestros datos <code>dataset.csv</code>. Recuerden que podemos hacer esto a través del comando <code>read.csv</code></p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1">data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;./datos/dataset.csv&quot;</span>)</a></code></pre></div>
<p>Primero, revisemos el tipo de variables contenidas en nuestra base de datos data. Recordemos que la función <code>str()</code> nos permite visualizar la estructura interna de un objeto en R. Otra función de diagnostico alternativa a <code>str()</code> es <code>summary()</code>.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" title="1"><span class="kw">str</span>(data)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    120 obs. of  9 variables:
##  $ Cultivo      : Factor w/ 1 level &quot;Arandanos&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Region       : Factor w/ 4 levels &quot;BioBio&quot;,&quot;La_Araucania&quot;,..: 4 4 4 4 4 4 4 4 4 4 ...
##  $ Variedad     : Factor w/ 2 levels &quot;V1&quot;,&quot;V2&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Hectareas    : num  1030 999 1118 1007 1078 ...
##  $ Temperatura  : num  16.8 16.9 15 15.7 15.1 15.9 16.1 15.6 17.4 14.7 ...
##  $ costo_jh     : int  13059 13026 12933 13027 13045 12949 13002 12968 12978 13056 ...
##  $ rendimiento  : num  6866 7122 7041 6892 6928 ...
##  $ Perdida_plaga: num  35.1 34.3 31.7 40.5 35.6 33 38.1 37.9 34.8 34.4 ...
##  $ mano_de_obra : int  3080 2728 3120 3135 3276 2966 2725 2874 2785 3193 ...</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" title="1"><span class="kw">summary</span>(data)</a></code></pre></div>
<pre><code>##       Cultivo             Region   Variedad   Hectareas     
##  Arandanos:120   BioBio      :30   V1:60    Min.   : 998.9  
##                  La_Araucania:30   V2:60    1st Qu.:1477.7  
##                  Maule       :30            Median :1797.0  
##                  Ohiggins    :30            Mean   :2090.7  
##                                             3rd Qu.:2352.7  
##                                             Max.   :3788.0  
##   Temperatura       costo_jh      rendimiento   Perdida_plaga  
##  Min.   :10.00   Min.   :11893   Min.   :4166   Min.   :24.70  
##  1st Qu.:12.50   1st Qu.:11997   1st Qu.:4765   1st Qu.:32.95  
##  Median :13.75   Median :12490   Median :5457   Median :34.60  
##  Mean   :13.74   Mean   :12500   Mean   :5617   Mean   :34.66  
##  3rd Qu.:15.10   3rd Qu.:13002   3rd Qu.:6285   3rd Qu.:37.30  
##  Max.   :17.40   Max.   :13121   Max.   :7247   Max.   :42.80  
##   mano_de_obra 
##  Min.   :2609  
##  1st Qu.:3092  
##  Median :3312  
##  Mean   :3384  
##  3rd Qu.:3645  
##  Max.   :4274</code></pre>
<div id="agreguemos-nuevas-variables" class="section level4">
<h4><span class="header-section-number">7.2.1.1</span> Agreguemos nuevas variables</h4>
<p>Agreguemos a nuestra base de datos la medición de 2 nuevas variables derivadas de una encuesta que se les hizo a los trabajadores en cada uno de los sitios de muestreo.</p>
<p>A ellos se les hicieron las siguientes preguntas:</p>
<ol style="list-style-type: lower-alpha">
<li><p>Durante los últimos seis meses ¿Usted ha aplicado algún tipo de herbicida de forma manual?</p></li>
<li><p>Durante el mismo periodo de tiempo ¿Usted ha experimentado algún problema de salud?</p></li>
</ol>
<p>Los resultados de la encuesta fueron los siguientes:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" title="1"><span class="co">#¿Ha aplicado algún herbicida de forma manual?</span></a>
<a class="sourceLine" id="cb182-2" title="2">data<span class="op">$</span>Uso_herbicida&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;SI&quot;</span>,<span class="st">&quot;SI&quot;</span>,<span class="st">&quot;SI&quot;</span>,<span class="st">&quot;SI&quot;</span>,<span class="st">&quot;NO&quot;</span>,<span class="st">&quot;NO&quot;</span>),<span class="dv">20</span>)</a>
<a class="sourceLine" id="cb182-3" title="3"></a>
<a class="sourceLine" id="cb182-4" title="4"><span class="co"># ¿Usted ha experimentado algún problema de salud?</span></a>
<a class="sourceLine" id="cb182-5" title="5">data<span class="op">$</span>Estado_salud&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;Enfermo&quot;</span>,<span class="st">&quot;Enfermo&quot;</span>,<span class="st">&quot;Sano&quot;</span>),<span class="dv">40</span>)</a></code></pre></div>
<p>Revisemos nuestra nueva base de datos</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="co"># Utilice str()</span></a>
<a class="sourceLine" id="cb183-2" title="2"><span class="kw">str</span>(data)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    120 obs. of  11 variables:
##  $ Cultivo      : Factor w/ 1 level &quot;Arandanos&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Region       : Factor w/ 4 levels &quot;BioBio&quot;,&quot;La_Araucania&quot;,..: 4 4 4 4 4 4 4 4 4 4 ...
##  $ Variedad     : Factor w/ 2 levels &quot;V1&quot;,&quot;V2&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Hectareas    : num  1030 999 1118 1007 1078 ...
##  $ Temperatura  : num  16.8 16.9 15 15.7 15.1 15.9 16.1 15.6 17.4 14.7 ...
##  $ costo_jh     : int  13059 13026 12933 13027 13045 12949 13002 12968 12978 13056 ...
##  $ rendimiento  : num  6866 7122 7041 6892 6928 ...
##  $ Perdida_plaga: num  35.1 34.3 31.7 40.5 35.6 33 38.1 37.9 34.8 34.4 ...
##  $ mano_de_obra : int  3080 2728 3120 3135 3276 2966 2725 2874 2785 3193 ...
##  $ Uso_herbicida: chr  &quot;SI&quot; &quot;SI&quot; &quot;SI&quot; &quot;SI&quot; ...
##  $ Estado_salud : chr  &quot;Enfermo&quot; &quot;Enfermo&quot; &quot;Sano&quot; &quot;Enfermo&quot; ...</code></pre>
</div>
</div>
<div id="analicemos-nuestros-datos-1" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Analicemos nuestros datos</h3>
<p>Estamos interesado en el bienestar de los trabajadores y nos preguntamos si el estado de salud de los trabajadores está asociado con la manipulación de herbicidas durante la jornada laboral. Para contestar esta pregunta, el investigador decide evaluar estadísticamente la (in)dependencia entre ambas variables. ¿Cómo lo hará?</p>
<p>Antes de realizar cualquier prueba estadística, es de extrema importancia analizar nuestros datos. Esto nos permitirá entender y evaluar la información contenida en nuestras variables.</p>
<p>Empecemos por ver un resumen de nuestros datos</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1">tabla_ind &lt;-<span class="st"> </span>data <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(Uso_herbicida,Estado_salud) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n=</span><span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-4" title="4"><span class="st">  </span><span class="kw">spread</span>(Estado_salud,n)</a>
<a class="sourceLine" id="cb185-5" title="5"></a>
<a class="sourceLine" id="cb185-6" title="6">tabla_ind</a></code></pre></div>
<pre><code>## # A tibble: 2 x 3
## # Groups:   Uso_herbicida [2]
##   Uso_herbicida Enfermo  Sano
##   &lt;chr&gt;           &lt;int&gt; &lt;int&gt;
## 1 NO                 20    20
## 2 SI                 60    20</code></pre>
<p>Otra forma de análisis es a través de un gráfico. Una forma de representar gráficamente una variable categórica es mediante el uso de barras. En R, la función barplot() nos permite visualizar la distribución o frecuencia de cada una de las categorías de una variable categórica.</p>
<p>Esta vez realicemos un gráfico a través de ggplot</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1"><span class="co"># Para graficar necesitaremos reordenar nuestros datos </span></a>
<a class="sourceLine" id="cb187-2" title="2"><span class="kw">ggplot</span>(data, <span class="kw">aes</span>(<span class="dt">x=</span>Estado_salud, <span class="dt">fill=</span>Uso_herbicida)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb187-3" title="3"><span class="st">  </span><span class="kw">geom_bar</span>()</a></code></pre></div>
<p><img src="07-lab_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="expresar-la-hipótesis-de-investigación-1" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Expresar la hipótesis de investigación</h3>
<p>El siguiente paso contempla expresar la pregunta o hipótesis de investigación en al menos dos hipótesis estadísticas contrastantes: nuestra hipótesis nula <span class="math inline">\(H_0\)</span> y nuestra hipótesis alternativa <span class="math inline">\(H_A\)</span>.</p>
<p>Para evaluar estadísticamente la relación entre ambas variables, podemos establecer el siguiente par de hipótesis:</p>
<p><span class="math display">\[
H_0: \text{No hay relación entre las variables Uso de Herbicida y Estado de Salud}\\
H_a: \text{Hay relación entre las variables}
\]</span></p>
<p>El objetivo es testear la veracidad de la <span class="math inline">\(H_0\)</span>. Para poner a prueba la <span class="math inline">\(H_0\)</span>, es necesario realizar una prueba estadística.</p>
</div>
<div id="calculemos-chi2-y-el-p-value-1" class="section level3">
<h3><span class="header-section-number">7.2.4</span> Calculemos <span class="math inline">\(\chi^2\)</span> y el p-value</h3>
<p>Las diferentes pruebas de hipótesis utilizan diferentes estadísticos de prueba según la distribución de probabilidad asumida en la <span class="math inline">\(H_0\)</span>. En el caso de la prueba de independencia de <span class="math inline">\(\chi^2\)</span> , el estadístico de la prueba se llamará estadístico de <span class="math inline">\(\chi^2\)</span>.</p>
<p>Calculemos el estadístico de <span class="math inline">\(\chi^2\)</span> y el <code>p-valor</code> para una prueba de independencia de utilizando las variables categóricas estado de salud y uso de herbicida:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" title="1">res_ind &lt;-<span class="st"> </span><span class="kw">chisq.test</span>(data<span class="op">$</span>Uso_herbicida, data<span class="op">$</span>Estado_salud)</a>
<a class="sourceLine" id="cb188-2" title="2">res_ind</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  data$Uso_herbicida and data$Estado_salud
## X-squared = 6.4172, df = 1, p-value = 0.0113</code></pre>
<p>Nuestro estadistico <span class="math inline">\(\chi^2\)</span> es igual a 6.4172, nuestros grados de libertad son 1 y el valor de probabilidad es de 0.0113</p>
</div>
<div id="conclusion-del-test" class="section level3">
<h3><span class="header-section-number">7.2.5</span> Conclusion del test</h3>
<p>Se rechaza la hipotesis nula. Por lo tanto, tenemos evidencia para sugerir que hay relación entre las variables Uso de Herbicida y Estado de Salud</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estadística-inferencial-pruebas-estadísticas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estadística-inferencial-regresión-lineal-y-correlación.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
